# Generated by Django 5.1.6 on 2025-03-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animals',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='animalsubtype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='breed',
            options={'managed': True},
        ),
    ]
