# Generated by Django 5.1.7 on 2025-03-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dryliquid', models.CharField(max_length=100)),
                ('nitrogen', models.FloatField()),
                ('phosphorous', models.FloatField()),
                ('potassium', models.FloatField()),
                ('sortnum', models.FloatField()),
            ],
            options={
                'db_table': 'fertilizers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FertilizerTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dryliquid', models.CharField(max_length=100)),
                ('custom', models.BooleanField()),
            ],
            options={
                'db_table': 'fertilizer_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FertilizerUnits',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dryliquid', models.CharField(max_length=100)),
                ('conversiontoimperialgallonsperacre', models.FloatField()),
                ('farmrequirednutrientsstdunitsconversion', models.FloatField()),
                ('farmrequirednutrientsstdunitsareaconversion', models.FloatField()),
            ],
            options={
                'db_table': 'fertilizer_units',
                'managed': True,
            },
        ),
    ]
