# Generated by Django 5.1.6 on 2025-03-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fertilizers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fertilizertypes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fertilizerunits',
            options={'managed': True},
        ),
    ]
