# Generated by Django 5.2.4 on 2025-07-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidFertilizerDensities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fertilizerid', models.IntegerField()),
                ('densityunitid', models.IntegerField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'liquid_fertilizer_densities',
                'managed': True,
            },
        ),
    ]
