# Generated by Django 5.2.4 on 2025-07-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizers', '0002_liquidfertilizerdensities'),
    ]

    operations = [
        migrations.CreateModel(
            name='DensityUnits',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('convfactor', models.FloatField()),
            ],
            options={
                'db_table': 'density_units',
                'managed': True,
            },
        ),
    ]
