# Generated by Django 5.2.5 on 2025-08-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizers', '0003_densityunits'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizers',
            name='fertigation',
            field=models.BooleanField(default=False),
        ),
    ]
