# Generated by Django 5.1.6 on 2025-03-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_add_yield_factor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crops',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='croptypes',
            options={'managed': True},
        ),
    ]
