# Generated by Django 5.1.6 on 2025-03-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_alter_crops_options_alter_croptypes_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YieldFactor',
        ),
    ]
