# Generated by Django 5.2.4 on 2025-07-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_plantsperacre'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceBetweenPlants',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'distance_between_plants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WhereWillPrunningsGo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'where_will_prunnings_go',
                'managed': True,
            },
        ),
    ]
