# Generated by Django 5.2.6 on 2025-09-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_distancebetweenplants_wherewillprunningsgo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilTestPhosphorousRanges',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('upperlimit', models.IntegerField()),
                ('rating', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'soil_test_phosphorous_ranges',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SoilTestPotassiumRanges',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('upperlimit', models.IntegerField()),
                ('rating', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'soil_test_potassium_ranges',
                'managed': True,
            },
        ),
    ]
