# Generated by Django 5.2.6 on 2025-09-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_distancebetweenplants_wherewillprunningsgo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BerryQuantities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('DistanceBetweenPlants', models.CharField(max_length=100)),
                ('PlantsPerAcre', models.IntegerField()),
            ],
            options={
                'db_table': 'berry_quantities',
                'managed': True,
            },
        ),
    ]
