# Generated by Django 5.2.7 on 2025-10-31 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0006_berryquantities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berryquantities',
            old_name='DistanceBetweenPlants',
            new_name='distancebetweenplants',
        ),
        migrations.RenameField(
            model_name='berryquantities',
            old_name='PlantsPerAcre',
            new_name='plantsperacre',
        ),
    ]
