# Generated by Django 5.1.6 on 2025-03-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidmaterialsconversionfactors',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='manures',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='solidmaterialsconversionfactors',
            options={'managed': True},
        ),
    ]
