# Generated by Django 5.2.4 on 2025-07-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manures', '0003_add_units_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='NitrogenMineralization',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('LocationId', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('FirstYearValue', models.FloatField()),
                ('LongTermValue', models.FloatField()),
            ],
            options={
                'db_table': 'nitrogen_mineralization',
                'managed': True,
            },
        ),
    ]
