# Generated by Django 5.2.5 on 2025-08-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manures', '0005_rename_nitrogenmineralization_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmmoniaRetentions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('seasonapplicationid', models.IntegerField()),
                ('drymatter', models.IntegerField()),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ammonia_retentions',
                'managed': True,
            },
        ),
    ]
