# Generated by Django 5.2.5 on 2025-09-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manures', '0006_ammoniaretentions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousYearManureApplications',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fieldmanureapplicationhistory', models.IntegerField()),
                ('defaultnitrogencredit', models.CharField(max_length=100)),
                ('previousyearmanureaplicationfrequency', models.IntegerField()),
            ],
            options={
                'db_table': 'previous_year_manure_applications',
                'managed': True,
            },
        ),
    ]
