# Generated by Django 5.2.7 on 2025-10-30 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manures', '0007_previousyearmanureapplications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solidmaterialsconversionfactors',
            old_name='metrictonsoutput',
            new_name='ustonsoutput',
        ),
    ]
