# Generated by Django 5.2.5 on 2025-09-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manures', '0007_previousyearmanureapplications'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidMaterialApplicationUsGallonsPerAcreRateConversions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('applicationrateunit', models.IntegerField()),
                ('applicationrateunitname', models.CharField(max_length=100)),
                ('usgallonsperacreconversion', models.FloatField()),
            ],
            options={
                'db_table': 'liquid_material_application_us_gallons_per_acre_rate_conversions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SolidMaterialApplicationCubicYardsPerAcreConversions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('applicationrateunit', models.IntegerField()),
                ('applicationrateunitname', models.CharField(max_length=100)),
                ('cubicyardsperacreconversion', models.FloatField()),
            ],
            options={
                'db_table': 'solid_material_application_cubic_yards_per_acre_conversions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SolidMaterialApplicationTonPerAcreRateConversions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('applicationrateunit', models.FloatField()),
                ('applicationrateunitname', models.CharField(max_length=100)),
                ('tonsperacreconversion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'solid_material_application_ton_per_acre_rate_conversions',
                'managed': True,
            },
        ),
    ]
