# Generated by Django 5.2.7 on 2025-11-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manures', '0008_add_material_application_conversions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solidmaterialsconversionfactors',
            old_name='metrictonsoutput',
            new_name='ustonsoutput',
        ),
    ]
