apiVersion: v1
kind: Template
parameters:
  - name: REPO
    value: nr-nmp
  - name: TARGET
    required: true
  - name: ENV
    required: true
  - name: DB_PASSWORD
    required: true
  - name: DB_USER
    required: true
  - name: DB_NAME
    required: true
  - name: DB_PORT
    required: true
  - name: SSO_CLIENT_ID
    required: true
  - name: SSO_CLIENT_SECRET
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      app: ${REPO}-${TARGET}
      name: ${REPO}-${TARGET}-database
    stringData:
      database-name: ${DB_NAME}
      database-password: ${DB_PASSWORD}
      database-port: ${DB_PORT}
      database-user: ${DB_USER}
  - apiVersion: v1
    kind: Secret
    metadata:
      app: ${REPO}-${TARGET}
      name: ${REPO}-backend-${TARGET}
    stringData:
      sso-client-id: ${SSO_CLIENT_ID}
      sso-client-secret: ${SSO_CLIENT_SECRET}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: nr-spar-backend-network-security-policy
    spec:
      podSelector: {}
      ingress:
        - from:
          - namespaceSelector:
              matchLabels:
                environment: ${ENV}
                name: fa23a0
      policyTypes:
        - Ingress
