/**
 * Returns the amount of solid manure generated by an animal type in a year, in tonnes. Returns -1 if the amount cannot be calculated.
 * @param solidPerPound The coefficient of solid manure per pound per animal per year
 * @param animalsPerFarm The average number of animals on the farm
 * @param daysCollected The number of days manure is collected
 */
function calculateSolidManurePerYear(solidPerPound: number, animalsPerFarm: number | undefined, daysCollected: number | undefined) {
  if (animalsPerFarm === undefined || daysCollected === undefined) {
    return -1;
  }
  return (animalsPerFarm * solidPerPound * daysCollected) / 2000;
}