# Generated by Django 5.2.7 on 2025-11-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NitrateCredit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('fromdatemonth', models.IntegerField()),
                ('todatemonth', models.IntegerField()),
            ],
            options={
                'db_table': 'nitratecredit',
                'managed': True,
            },
        ),
    ]
