# Generated by Django 5.1.6 on 2025-03-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_regions_options_alter_subregion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
