# Generated by Django 5.1.5 on 2025-02-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('covercrop', models.BooleanField()),
                ('crudeproteinrequired', models.BooleanField()),
                ('customcrop', models.BooleanField()),
                ('modifynitrogen', models.BooleanField()),
            ],
        ),
    ]
