# Generated by Django 5.1.5 on 2025-02-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('covercrop', models.BooleanField()),
                ('crudeproteinrequired', models.BooleanField()),
                ('customcrop', models.BooleanField()),
                ('modifynitrogen', models.BooleanField()),
            ],
            options={
                'db_table': 'crop_types',
                'managed': False,
            },
        ),
    ]
