# Generated by Django 5.1.6 on 2025-03-03 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nitrogen', models.FloatField()),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.croptypes')),
            ],
        ),
    ]
