# Generated by Django 5.1.5 on 2025-02-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptypes',
            name='test',
            field=models.BooleanField(null=True),
        ),
    ]
