name: Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'  # Only run on Python file changes

jobs:
  lint:
    name: Run Python Linting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Build and start Docker containers
        run: |
          docker compose up -d backend
          
      - name: Run lint command from root Makefile
        run: |
          make lint 