name: Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'  # Only run on Python file changes

jobs:
  lint:
    name: Run Python Linting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint pylint-django
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
          
      - name: Run linting
        working-directory: backend
        run: |
          # Set PYLINTHOME to a writable location
          export PYLINTHOME=$(pwd)/.pylint.d
          # Run the existing make lint command
          make lint 