name: Backend Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'  # Only run on Python file changes

jobs:
  lint:
    name: Run Python Linting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint pylint-django
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
          
      - name: Run flake8
        working-directory: backend
        run: |
          python -m flake8 --config=.flake8
          
      - name: Run pylint
        working-directory: backend
        run: |
          export PYLINTHOME=$(pwd)/.pylint.d  # Set writable cache location
          python -m pylint --rcfile=.pylintrc --load-plugins=pylint_django --django-settings-module=config.settings --ignore=migrations apps 